---
title: "Uso de R para consultas MySQL"
output: github_document
---

## 1) Librerias necesarias para la conexión.

```{r libraries, , results='hide', message=FALSE, warning=FALSE}

#Necesarias para la conexión de R - MySQL TEST
library(DBI) 
library(RMariaDB)

#En caso de desear hacer consultas y manipular los datos usando la lógica dplyr
library(dplyr)
library(dbplyr)

#Librerias de formato para visualizar la información
library(flextable)
library(formattable)
library(ggplot2)
library(knitr)

```

## 2) Conexión a una base de datos de MySQL desde R

```{r conexion}

con <- dbConnect(
  RMariaDB::MariaDB(),
  host     = "localhost",
  port     = 3306,
  user     = "root", #colocar usario MySQL
  password = rstudioapi::askForPassword("MySQL password"), #Ventana emergente para solicitar password
  dbname   = "StudentsPerformance_OfficialDB" #Cambiar aqui por la base de datos que se desea conectar
)

```

## 3) Revisar las tablas existentes en la base de datos asi como los atributos de cada tabla:

```{r detalle1}

dbListTables(con) #Revisa tablas en la base de datos
dbListFields(con, "Grades") #Revisa los atributos de una de las tablas

```


## 4) Consulta a la base de datos manteniendo el languaje SQL:

```{r detalle2, message=FALSE, warning=FALSE, fig.align ='center'}

dbReadTable(con, "School") #Extrae todos los datos de una de las tablas

formattable(dbReadTable(con, "School"))


califs <- dbGetQuery(con, "SELECT * FROM Grades")
knitr::kable(head(califs))


res <- dbGetQuery(con, "
  SELECT student_id, course_id, G3
  FROM Grades
  WHERE G3 > 15
  LIMIT 10
")

knitr::kable(res)


```

## 5) Creación de tablas

```{r detalle3, fig.align='center'}

df <- data.frame(
  name = c("Ana", "Luis", "María"),
  score = c(10, 11, 12)
)

dbWriteTable(
  con,
  "scores",
  df,
  overwrite = TRUE,
  field.types = c(name = "VARCHAR(20)", score = "INT")
)

#La tabla nueva creada en la base de datos se ve de la siguiente manera:
flextable(dbGetQuery(con, "SELECT * FROM scores"))

new_df <- data.frame(
  name = c("Carlos", "Elena"),
  score = c(13, 14)
)

dbWriteTable(con, "scores", new_df, append = TRUE)
#Aquí usamos append = TRUE para añadir filas sin eliminar lo ya existente

#La tabla nueva creada con los nuevos registros en la base de datos se ve de la siguiente manera:
flextable(dbGetQuery(con, "SELECT * FROM scores"))

```

## 6) Creación de tablas

```{r detalle4}

# Verifica que la tabla existe, en caso de que si, borrarla

if ( dbExistsTable(con, "scores") == TRUE) { dbRemoveTable(con, "scores") }

```

## 7) Uso de dplyr para consultas

```{r detalle5, fig.align='center' , message=FALSE, warning=FALSE}

grades_tbl <- tbl(con, "Grades")

grades_high <- grades_tbl %>%
  filter(G3 > 0) %>%
  select(student_id, course_id, G3) %>%
  collect()

head(grades_high)

hist(grades_high$G3)

ggplot(grades_high, aes(x = G3)) +
  geom_histogram(binwidth = 1, fill = "steelblue", color = "white") +
  labs(title = "Distribución de Calificaciones (G3)",
       x = "Calificación",
       y = "Frecuencia") +
  theme_minimal()

```


## 9) Importante al final, desconectar la sesión

```{r detalle6}

  dbDisconnect(con)

```
